spring:
  # h2:
  #   console:
  #     enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/xipptech
    username: xipptech
    password: xt123456
    driver-class-name: org.postgresql.Driver
    
  jpa:
    # database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update # create-drop # update